### PR TITLE
Upgrade Android libraries

### PR DESCRIPTION
**Pull request by emilkarl**
Extended @mikebridge's work and using newer packages to support React Native 0.58+ and also using the latest versions of google firebase libraries and pushers android lib.

### CODE REVIEW

**Comment by mikebridge** [comment]
It was a difficult upgrade to RN 0.59 and I bumped up a lot of the versions (e.g. android 28) while flailing with compatibility issues.  I'm not sure what minimum compatibility level should be for Android and RN.

**Comment by emilkarl** [comment]
We're using android 28 and RN 0.59 and it works very good.

**Comment by stephenkiers** [comment]
I have reproduced most of this in #48 Would you be willing to review it?

**Comment by b8ne** [comment]
Closing this as it appears all has been added in #48

**Pull request closed without merging**
